openapi: 3.0.0
info:
  title: Audio API
  description: An API for managing audio files
  version: 1.0.0
servers:
  - url: https://api.example.com
    description: Main production server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT # Optional, signals use of JWT
  schemas:
    Audio:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        url:
          type: string
    NewAudio:
      type: object
      properties:
        name:
          type: string
        description:
          type: string

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    NotFoundError:
      description: Resource not found
    ValidationError:
      description: Invalid request parameters

security:
  - bearerAuth: [] # Apply globally where needed

paths:
  /audio:
    get:
      summary: Get a list of audio files
      description: Retrieve a list of public audio files
      responses:
        "200":
          description: A list of audio files
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Audio"

    post:
      summary: Upload a new audio file
      description: Upload a new audio file (protected route)
      security:
        - bearerAuth: [] # JWT required
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewAudio"
      responses:
        "201":
          description: Audio file created successfully
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "400":
          $ref: "#/components/responses/ValidationError"

  /audio/{id}:
    get:
      summary: Get details of a specific audio file
      description: Retrieve a specific audio file by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID of the audio file
      responses:
        "200":
          description: Details of the audio file
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Audio"
        "404":
          $ref: "#/components/responses/NotFoundError"

    patch:
      summary: Update (rename) an audio file
      description: Rename or update fields of an audio file (protected route)
      security:
        - bearerAuth: [] # JWT required
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID of the audio file to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        "200":
          description: Audio file updated successfully
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"

  /audio/{id}/rename:
    post:
      summary: Rename an audio file
      description: Rename an audio file by ID (legacy or alternative route, protected)
      security:
        - bearerAuth: [] # JWT required
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID of the audio file to rename
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: New name of the audio file
      responses:
        "200":
          description: Audio file renamed successfully
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
