openapi: 3.0.0
info:
  title: KevBot API
  description: API for managing KevBot tracks, playlists, and more!
  version: 1.0.0
components:
  parameters:
    id:
      in: path
      name: id
      required: true
      schema:
        type: integer
  schemas:
    Playlist:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        dt_created:
          format: date-time
          type: string
        user_id:
          type: integer
        tracks:
          items:
            $ref: "#/components/schemas/Track"
          type: array
    Track:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        dt_created:
          format: date-time
          type: string
        user_id:
          type: integer
        duration:
          type: number
    TrackPatch:
      type: object
      properties:
        name:
          type: string
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
paths:
  # todo: review login
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                password:
                  type: string
                username:
                  type: string
              required:
                - username
                - password
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  token:
                    type: string
                type: object
          description: JWT token retrieved
      summary: Login and retrieve a JWT token
  # todo: review playlists
  /playlists:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Playlist"
                type: array
          description: List of playlists
      summary: Retrieve a list of playlists
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                tracks:
                  items:
                    type: string
                  type: array
              required:
                - name
              type: object
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Playlist"
          description: Playlist created
      security:
        - bearerAuth: []
      summary: Create a new playlist
  # todo: review search
  /search:
    get:
      parameters:
        - in: query
          name: query
          required: true
          schema:
            type: string
        - in: query
          name: type
          schema:
            enum:
              - track
              - playlist
            type: string
        - in: query
          name: artist
          schema:
            type: string
        - in: query
          name: album
          schema:
            type: string
        - in: query
          name: genre
          schema:
            type: string
        - in: query
          name: name
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  oneOf:
                    - $ref: "#/components/schemas/Track"
                    - $ref: "#/components/schemas/Playlist"
                type: array
          description: Search results
      summary: Search for tracks or playlists
  /tracks:
    get:
      parameters:
        - in: query
          name: name
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Track"
                type: array
          description: List of tracks
      summary: Retrieve a list of available tracks
    post:
      summary: Upload a new track
      description: Upload a new audio track file along with a name.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "The name of the track"
                file:
                  type: string
                  format: binary
                  description: "The audio file to upload"
            encoding:
              file:
                contentType: audio/mpeg
      responses:
        "201":
          description: "Track was created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Track"
        "400":
          description: "Bad request, invalid input"
        "500":
          description: "Internal server error"
    # post:
    #   requestBody:
    #     content:
    #       application/json:
    #         schema:
    #           $ref: "#/components/schemas/Track"
    #   responses:
    #     "201":
    #       content:
    #         application/json:
    #           schema:
    #             $ref: "#/components/schemas/Track"
    #       description: Track uploaded
    #   security:
    #     - bearerAuth: []
    #   summary: Upload a new track
  /tracks/{id}:
    parameters:
      - $ref: "#/components/parameters/id"
    delete:
      responses:
        "204":
          description: Track deleted
      security:
        - bearerAuth: []
      summary: Delete a track
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Track"
          description: Track metadata
      summary: Retrieve metadata for a specific track
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TrackPatch"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Track"
          description: Track metadata updated
      security:
        - bearerAuth: []
      summary: Update track metadata
  /tracks/{id}/download:
    get:
      responses:
        "200":
          description: Track download initiated
      summary: Download a specific track
  /tracks/{id}/stream:
    get:
      responses:
        "200":
          description: Track stream initiated
      summary: Stream a specific track
  /users/{id}:
    parameters:
      - $ref: "#/components/parameters/id"
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  created_at:
                    format: date-time
                    type: string
                  email:
                    type: string
                  id:
                    type: string
                  username:
                    type: string
                type: object
          description: User profile information
      summary: Retrieve user profile information
  /users/{id}/history:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Track"
                type: array
          description: User's listening history
      summary: Retrieve the user's listening history
  /users/{id}/playlists:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Playlist"
                type: array
          description: List of user's playlists
      summary: Retrieve the user's playlists
  /users/{id}/tracks:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Track"
                type: array
          description: List of tracks associated with the user
      summary: Retrieve tracks associated with the user
security:
  - bearerAuth: []
servers:
  - url: https://api.example.com/v1
