name: Node Continuos Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    env:
      ADDRESS: 127.0.0.1
      PORT: 3000
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout head of main
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Clean install of node packages
        run: npm ci
      - name: Run tests
        run: npm run ci-test
