services:
  tools:
    build:
      context: ../tools
      dockerfile: ./Dockerfile.dev
    container_name: tools
    command: sleep infinity
    ports:
      - 80:80 # needed?
    volumes:
      - ..:/src
