# Use the official Python base image
FROM python:3.12.3-slim

# Set environment variables to avoid prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update and install necessary packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends default-mysql-client && \
    apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory and copy code, note, docker-compose mounts host src to src-dev
WORKDIR /src
COPY . .

# install virtualenv
RUN pip install virtualenv

# setup venv for migration_manager
RUN cd ./db/migration_manager && \
    rm -rf .venv && \
    python -m virtualenv .venv && \
    .venv/bin/python -m pip install --no-cache-dir -r requirements.txt

# setup venv for rename_to_id
RUN cd ./db/rename_to_id && \
    rm -rf .venv && \
    virtualenv .venv && \
    .venv/bin/python -m pip install --no-cache-dir -r requirements.txt