# syntax=docker/dockerfile:1

FROM node:18.12.1-alpine
ENV NODE_ENV=production

WORKDIR /src

RUN apk add make
RUN apk add libtool
RUN apk add libsodium
RUN apk add autoconf
RUN apk add automake
RUN apk add g++
RUN apk add --no-cache python3 py3-pip
RUN npm install node-gyp -g

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install --omit-dev

COPY . .

CMD [ "npm", "start" ]