name: "[Database (gcloud)] Rename audio name to id"

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment
        description: Select environment

jobs:
  migrate-database:
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
      - name: Echo configuration
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "Environment: ${{ inputs.environment }}"

      - name: Checkout the selected branch or tag
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd $GITHUB_WORKSPACE/tools
          docker build -f Dockerfile.dev -t kevbot_tools .

      - name: Create .env file
        run: |
          cd $GITHUB_WORKSPACE/tools
          echo "MYSQL_TCP_PORT=${{ secrets.MYSQL_TCP_PORT }}" > .env
          echo "MYSQL_ROOT_USER=${{ secrets.MYSQL_ROOT_USER }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> .env
          echo "GCP_SERVICE_ACCOUNT_JSON_64=${{ secrets.GCP_SERVICE_ACCOUNT_JSON_64 }}" >> .env
          echo "GCP_AUDIO_BUCKET=${{ secrets.GCP_AUDIO_BUCKET }}" >> .env

      - name: Run migration
        run: |
          cd $GITHUB_WORKSPACE/tools
          docker run --rm --env-file .env kevbot_tools bash -c "cd /src/db/rename_to_id && .venv/bin/python rename_to_id -y"
