name: "[Database] Migrate"

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment
        description: Select environment
      migration_version:
        required: true
        type: string
        description: Migration version

jobs:
  migrate-database:
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    env:
      MIGRATION_VERSION: ${{ inputs.migration_version }}

    steps:
      - name: Echo configuration
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "Migration Version: ${{ inputs.migration_version}}"

      - name: Decode base64 encoded secrets
        run: echo "GCP_SERVICE_ACCOUNT_JSON=$(echo '${{ secrets.GCP_SERVICE_ACCOUNT_JSON_64 }}' | base64 --decode)" >> $GITHUB_ENV

      - name: Checkout the selected branch or tag
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd $GITHUB_WORKSPACE/tools
          docker build -f Dockerfile.dev -t kevbot_tools .

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_SERVICE_ACCOUNT_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get mysql test data from Google Cloud Storage
        run: |
          gsutil cp gs://${{ secrets.GCP_SENSITIVE_DATA_BUCKET }}/${{ secrets.GCP_MYSQL_TEST_DATA_FILE }} $GITHUB_WORKSPACE/db/migration/sensitive_supplemental_scripts/${{ secrets.GCP_MYSQL_TEST_DATA_FILE }}

      - name: Create .env file
        run: |
          cd $GITHUB_WORKSPACE/tools
          echo "MYSQL_TCP_PORT=${{ secrets.MYSQL_TCP_PORT }}" > .env
          echo "MYSQL_ROOT_USER=${{ secrets.MYSQL_ROOT_USER }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> .env
          echo "GCP_SERVICE_ACCOUNT_JSON_64=${{ secrets.GCP_SERVICE_ACCOUNT_JSON_64 }}" >> .env
          echo "GCP_AUDIO_BUCKET=${{ secrets.GCP_AUDIO_BUCKET }}" >> .env
          echo "PATH_TO_RENAMETOID_MODULE=/src/db/rename_to_id" >> .env

      - name: Run migration
        run: |
          cd $GITHUB_WORKSPACE/tools
          docker run --rm --env-file .env -v $GITHUB_WORKSPACE/db/migration:/src/db/migration_manager/migration kevbot_tools bash -c "cd /src/db/migration_manager && .venv/bin/python migration_manager migrate -v $MIGRATION_VERSION --schema-dir ./migration/schema_change_scripts --supplemental-dirs ./migration/supplemental_scripts ./migration/sensitive_supplemental_scripts"
