name: Lint PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install commitlint CLI
        run: npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Lint PR Title with commitlint
        run: |
          echo "${{ github.event.pull_request.title }}" | commitlint --config commitlint.config.js
