name: Provision Droplet

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select environment
  push:

jobs:
  provision:
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DIGITAL_OCEAN_DROPLET_PRIVATE_SSH_KEY }}

      # - name: Provision Droplet
      #   # https://docs.docker.com/engine/install/ubuntu/
      #   run: |
      #     ssh -o StrictHostKeyChecking=no root@${{ secrets.DIGITAL_OCEAN_DROPLET_IP }} <<EOF
      #     sudo apt-get update
      #     sudo apt-get install ca-certificates curl
      #     sudo install -m 0755 -d /etc/apt/keyrings
      #     sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      #     sudo chmod a+r /etc/apt/keyrings/docker.asc
      #     echo \
      #       "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      #       $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      #       sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      #     sudo apt-get update
      #     EOF

      - name: Hello world
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DIGITAL_OCEAN_DROPLET_IP }} <<EOF
          touch hello-world.txt
          exit
          EOF
