name: "[Service] Stop and Clean Up"

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment
        description: Select environment
      service_name:
        type: choice
        required: true
        description: Service name
        options:
          - db
jobs:
  stop-and-clean-up-service:
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    env:
      SSH_USER: root
      SSH_IP_OR_HOST: ${{ secrets.DIGITAL_OCEAN_DROPLET_IP }}
      SERVICE_NAME: ${{ inputs.service_name }}
      SERVICE_WORKSPACE: /srv/KevBot/$SERVICE_NAME

    steps:
      - name: Echo configuration
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "Service: ${{ inputs.service_name }}"

      - name: Decode base64 encoded secrets
        run: |
          echo "DIGITAL_OCEAN_DROPLET_PRIVATE_SSH_KEY<<EOF" >> $GITHUB_ENV
          echo "$(echo '${{ secrets.DIGITAL_OCEAN_DROPLET_PRIVATE_SSH_KEY_64  }}' | base64 --decode)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ env.DIGITAL_OCEAN_DROPLET_PRIVATE_SSH_KEY }}

      - name: Stop docker service
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_IP_OR_HOST << EOF
            cd $SERVICE_WORKSPACE
            docker compose --env-file .env down --volumes --rmi all 
          EOF
