name: Stop Service

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment
        description: Select environment
      service_name:
        type: choice
        required: true
        description: Service name
        options:
          - db
jobs:
  deploy-service:
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    env:
      SSH_USER: root
      SSH_IP_OR_HOST: ${{ secrets.DIGITAL_OCEAN_DROPLET_IP }}
      SERVICE_NAME: ${{ inputs.service_name }}
      SERVICE_WORKSPACE: /srv/KevBot/$SERVICE_NAME

    steps:
      - name: Echo configuration
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "Service: ${{ inputs.service_name }}"

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DIGITAL_OCEAN_DROPLET_PRIVATE_SSH_KEY }}

      - name: Stop docker service
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_IP_OR_HOST << EOF
            cd $SERVICE_WORKSPACE
            docker compose down
          EOF
